AdamsLair/duality

- Duality/ContentProvider.cs
- Duality/Resource.cs
- DualityEditor/FileEventManager.cs
- DualityEditorPlugins/ProjectView/Modules/ProjectFolderView.cs
I believe 'ressource' is the French spelling. This change is for consistency.
> fixed English misspelling of 'resource'

- SampleProjects/BasicMenu/BasicMenu.csproj
- SampleProjects/BasicMenu/Components/MenuAnotherChangeColor.cs
- SampleProjects/BasicMenu/Components/MenuChangeVolume.cs
- SampleProjects/BasicMenu/Components/MenuQuitConfirm.cs
- SampleProjects/BasicMenu/Components/MenuSwitchToPage.cs
- SampleProjects/BasicMenu/Content/AppData.dat
- SampleProjects/BasicMenu/Content/Data/BasicMenu/OverlayGameObjectMenu.Scene.res
- SampleProjects/BasicMenu/Controllers/EventMenuController.cs
- SampleProjects/BasicMenu/CorePlugin.cs
- SampleProjects/BasicMenu/MenuComponent.cs
- SampleProjects/BasicMenu/VolumeRenderer.cs
Extended the basic menu sample with another menu, used to show the interaction with something more interactive like a volume control
> Menu sample extended

- DualityEditor/DualityEditor.csproj
- DualityEditor/Properties/AssemblyInfo.cs
- DualityEditor/packages.config
- DualityEditorPlugins/EditorBase/EditorBase.Editor.csproj
- DualityEditorPlugins/EditorBase/packages.config
- DualityEditorPlugins/PackageManagerFrontend/PackageManagerFrontend.Editor.csproj
- DualityEditorPlugins/PackageManagerFrontend/packages.config
- DualityEditorPlugins/ProjectView/ProjectView.Editor.csproj
- DualityEditorPlugins/ProjectView/packages.config
- DualityEditorPlugins/SceneView/SceneView.Editor.csproj
- DualityEditorPlugins/SceneView/packages.config
- NuGetPackageSpecs/Duality.Editor.nuspec
#FIX: Fixed tree / list view scrolling behavior not accounting for hidden or filtered items.
> TreeView Scrolling Bugfixes

- Duality/Components/Renderers/AnimSpriteRenderer.cs
- Duality/Components/Renderers/SpriteRenderer.cs
Updated version of this: http://forum.adamslair.net/viewtopic.php?f=4&t=433
> Added FlipHorizontal and FlipVertical

- DualityEditor/Utility/Extensions/ExtMethodsDualityFont.cs
Now it accepts the ExtendedSet data container which allows to modify set of characters which will be drawn.
http://forum.adamslair.net/viewtopic.php?f=4&t=715#p4282
> Extended RenderGlyphs method

- DualityPlugins/Tilemaps/Tilemaps/Components/ICmpTilemapRenderer.cs
- DualityPlugins/Tilemaps/Tilemaps/Components/TilemapRenderer.cs
> #384 Tile position to local position in ICmpTilemapRenderer

- DualityEditorPlugins/CamView/CamViewStates/CamViewState.cs
> Removed camera rotation in CameraView

- DualityPlugins/Tilemaps/Tilesets/Tileset.cs
Fixes #404 
But will leave a weird Tile palette 
It's possible to paint with this "new tileset"
But applying the changes of the tileset will change it to Checkerboard correctly
> Fix issue 404

- Samples/BasicMenu/MenuComponent.cs
- Samples/CameraController/ExampleSceneController.cs
- Samples/DualStickSpaceShooter/Gameplay/Bullet.cs
- Samples/DualStickSpaceShooter/Gameplay/EnemyClaymore.cs
- Samples/DualStickSpaceShooter/Gameplay/Player.cs
- Samples/DualStickSpaceShooter/Gameplay/Ship.cs
- Samples/DualStickSpaceShooter/Visuals/ParticleEffect.cs
- Samples/DualStickSpaceShooter/Visuals/ParticleEmitter.cs
- Samples/FlapOrDie/Components/Ticker.cs
- Samples/FlapOrDie/Controllers/GameController.cs
- Samples/FlapOrDie/Controllers/PlayerController.cs
- Samples/ParticleSystem/ParticleEffect.cs
- Samples/ParticleSystem/ParticleEmitter.cs
- Samples/Tilemaps/RpgLike/ActorAnimator.cs
- Source/Core/Duality/Audio/SoundInstance.cs
- Source/Core/Duality/Components/Diagnostics/ProfileRenderer.cs
- Source/Core/Duality/Components/Physics/Joints/LineJointInfo.cs
- Source/Core/Duality/Components/Physics/Joints/PrismaticJointInfo.cs
- Source/Core/Duality/Components/Physics/Joints/RevoluteJointInfo.cs
- Source/Core/Duality/Components/Physics/RigidBody.cs
- Source/Core/Duality/Components/Renderers/AnimSpriteRenderer.cs
- Source/Core/Duality/Resources/Scene.cs
- Source/Core/Duality/Time.cs
- Source/Core/Duality/Utility/Log/VisualLogEntry.cs
- Source/Core/Duality/Utility/Math/PhysicsConvert.cs
- Source/Core/Duality/Utility/Profiling/TimeCounter.cs
- Source/Platform/DefaultOpenTK/Backend/Graphics/NativeWindow.cs
Changes in Time.cs according to issue #448
> Changes in Time.cs according to issue #448

- Source/Core/Duality/Components/Renderers/AnimSpriteRenderer.cs
- Set default of animFrameCount to 1
- Prevent user from setting animFrameCount below 1
- Update EditorHintRange
Issue #453
> Update AnimFrameCount default to 1

- Source/Editor/DualityEditor/PackageManagement/PackageManager.cs
> Map non Duality packages 'content' to project root

- Source/Core/Duality/GameObject.cs
First go at open-source contribution, I took a shot at fixing issue #505.
> Fixes an issue with creating null-named GameObjects through code (505)

- Source/Editor/DualityEditor/Controls/AutoExpandTreeView.cs
- Source/Editor/DualityEditor/DualityEditor.csproj
- Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsTreeNodeAdv.cs
- Source/Plugins/EditorModules/ProjectView/Modules/ProjectFolderView.Designer.cs
- Source/Plugins/EditorModules/SceneView/Modules/SceneView.Designer.cs
I went with the approach to extend TreeViewAdv and used the new class in both ProjectFolderView and SceneView. I tried to keep the changes as minimal as possible although the solution and csproj seem to have run away from a simple add existing file, let me know if I should remove them.
A few questions\comments:
1. Do you want to keep consistency of the type held by the SceneView\ProjectFolderView? I have currently kept the type as TreeViewAdv and just newed it to the new type (AutoExpandTreeView) which has a default of 1000 ms delay.
2. Is there a place to provide user\editor preferences, I would suggest putting the delay as an option for users. 
3. Have fun reviewing <3
4. Should I add automated testing?
Manual Tests:
> Auto-Expand sub-folder when dragging over it. Issue #492

- Source/Core/Duality/Drawing/Canvas.cs
- Source/Core/Duality/Drawing/CanvasState.cs
Fixes issue #517.
Tested and all
> Fixes issue#517

- .gitignore
- Source/Core/Duality/Components/Camera.cs
- Source/Core/Duality/Resources/Scene.cs
For some graphic effects the order in which cameras render can be important.
> Camera priority

- Source/Core/Duality/DualityApp.cs
> Fixed Time.GameTimer related bug in DualityApp.Update

- Source/Core/Duality/Backend/Dummy/DummyAudioBackend.cs
- Source/Core/Duality/Backend/Dummy/DummyGraphicsBackend.cs
- Source/Core/Duality/Backend/Dummy/DummySystemBackend.cs
> Added logs to dummy backend initialization

- Source/Core/Duality/Backend/DefaultPluginLoader.cs
- Source/Core/Duality/Component.cs
- Source/Core/Duality/Duality.csproj
- Source/Core/Duality/GameObject.cs
- Source/Core/Duality/Serialization/UniqueIdentifyableHelper.cs
- Source/Core/Primitives/Math/MathF.cs
- Test/Core/Serialization/SerializerTest.cs
> New unique identifier

- Source/Editor/DualityEditor/DualityEditorApp.cs
Duality now opens the last open scene. TODO:
> #445: duality now opens the last open scene

- Samples/Steering/Agent/Agent.cs
- Samples/Steering/HelperComponents.cs
- Samples/Steering/Targets/ISteeringTarget.cs
- Samples/Steering/VelocitySampler/AdaptiveVelocitySampler.cs
- Samples/Steering/VelocitySampler/IVelocitySampler.cs
Fixed various comment errors and typos within the steering sample project as mentioned in #614 . Besides correcting one property which had a comment copy and pasted from another property, the changes are only simple typo corrections.
> Steering sample comment fixes

- Source/Core/Duality/Drawing/FormattedText.cs
- Source/Plugins/EditorBase/Importers/FontAssetImporter.cs
Couple of simple improvements:
- Added unicode character capability to **FormattedText**
- otf (OpenType Font) import suport for **FontAssetImporter**
> More text goodies

- Source/Core/Duality/Drawing/BatchInfo.cs
- Source/Core/Duality/Drawing/ShaderParameterCollection.cs
Nothing special, just a Count property (that works even if the list is still null) for ShaderParameterCollection, and a way to set a number of parameters to a BatchInfo in batch.
> Convenience method and properties for ShaderParameterCollection and BatchInfo

- Source/Plugins/Tilemaps/Core/Tilemaps.Core.csproj
- Source/Plugins/Tilemaps/Core/Tilemaps/TilemapFloodFill.cs
- Source/Plugins/Tilemaps/Editor/CamViewStates/TilemapTools/FillTilemapTool.cs
https://github.com/AdamsLair/duality/issues/612
> Extract flood fill algorithm from FillTilemapTool

- Source/Editor/DualityEditor/DualityEditorApp.cs
- Source/Editor/DualityEditor/Extensibility/EditorActions/EditorAction.cs
- Source/Editor/DualityEditor/Extensibility/EditorActions/EditorSingleAction.cs
- Source/Editor/DualityEditor/Extensibility/EditorActions/IEditorAction.cs
- Source/Editor/DualityEditor/Extensibility/Previews/IPreviewGenerator.cs
- Source/Editor/DualityEditor/Extensibility/Previews/PreviewGenerator.cs
- Source/Editor/DualityEditor/Extensibility/Previews/PreviewSizeMode.cs
- Source/Editor/DualityEditor/HelpSystem/HelpInfo.cs
- Source/Editor/DualityEditor/HelpSystem/IHelpProvider.cs
- Source/Editor/DualityEditor/PreviewProvider.cs
Added XmlDoc comments to various parts of the editor code, focusing on classes that users may run across when extending the editor.
Covered:
* DualityEditorApp.ObjectPropertyChanged
* Editor actions
* Preview system
* HelpInfo system
> Editor Documentation

- Source/Core/Duality/Components/Renderers/SpriteRenderer.cs
> Fix for #669

- Source/Editor/DualityEditor/Forms/ListSelectionDialog.Designer.cs
- Source/Editor/DualityEditor/Forms/ListSelectionDialog.cs
Addresses issue #749 
Disables the OK button if no text is present in the filter. Additionally, disables the OK button if no node is currently selected from the list.
> Prevents null exception when selecting component type

- README.md
We are back in active development!
> Updated maintenance notice

- appveyor.yml
> Switched to vs2019 appveyor image

- Build/NuGetPackageSpecs/AudioHandling.Sample.nuspec
- Build/NuGetPackageSpecs/BasicMenu.Sample.nuspec
- Build/NuGetPackageSpecs/BasicShaders.Sample.nuspec
- Build/NuGetPackageSpecs/Benchmarks.Sample.nuspec
- Build/NuGetPackageSpecs/CameraController.Sample.nuspec
- Build/NuGetPackageSpecs/CustomRenderingSetup.Sample.nuspec
- Build/NuGetPackageSpecs/DualStickSpaceShooter.Sample.nuspec
- Build/NuGetPackageSpecs/DynamicLighting.Sample.nuspec
- Build/NuGetPackageSpecs/FlapOrDie.Sample.nuspec
- Build/NuGetPackageSpecs/InputHandling.Sample.nuspec
- Build/NuGetPackageSpecs/ParticleSystem.Sample.nuspec
- Build/NuGetPackageSpecs/Physics.Sample.nuspec
- Build/NuGetPackageSpecs/SmoothAnimation.Sample.nuspec
- Build/NuGetPackageSpecs/Steering.Sample.nuspec
- Build/NuGetPackageSpecs/Tilemaps.Sample.nuspec
> Added links to the sample projects for the sample nuspecs

- Source/DualityTemplates/DualityTemplates.csproj
Now copies the template nupkg to Build\NightlyBuild\NuGetPackages and generates a package when building
> Copy nuget package to nugetpackage output and create nuget packag on build

- Source/Editor/DualityEditor/Utility/EditorHelper.cs
Fixes sln file not being found since its now located in the root
> Now the open source button looks recursively from the root for a .sln file

- Directory.Build.props
- Source/Core/Duality/Duality.csproj
- Source/Core/Primitives/DualityPrimitives.csproj
- Source/Editor/DualityEditor/DualityEditor.csproj
- Source/Editor/Updater/DualityUpdater.csproj
- Source/Launcher/DualityLauncher.csproj
- Source/Platform/DefaultOpenTK/DefaultOpenTK.Core.csproj
- Source/Platform/DefaultOpenTKEditor/DefaultOpenTK.Editor.csproj
- Source/Platform/DotNetFramework/DotNetFramework.Core.csproj
- Source/Plugins/Compatibility/Compatibility.Core.csproj
- Source/Plugins/EditorBase/EditorBase.Editor.csproj
- Source/Plugins/EditorModules/CamView/CamView.Editor.csproj
- Source/Plugins/EditorModules/HelpAdvisor/HelpAdvisor.Editor.csproj
- Source/Plugins/EditorModules/LogView/LogView.Editor.csproj
- Source/Plugins/EditorModules/ObjectInspector/ObjectInspector.Editor.csproj
- Source/Plugins/EditorModules/ProjectView/ProjectView.Editor.csproj
- Source/Plugins/EditorModules/SceneView/SceneView.Editor.csproj
- Source/Plugins/Tilemaps/Core/Tilemaps.Core.csproj
- Source/Plugins/Tilemaps/Editor/Tilemaps.Editor.csproj
- Test/Core/DualityTests.csproj
- Test/Editor/DualityEditorTests.csproj
- Tools/NightlyBuilder/NightlyBuilder.csproj
- Tools/VersionUpdater/VersionUpdater.csproj
While adding a benchmarkdotnet project I noticed some problems when using the dotnet cli. This PR aims to fix these problems:
- SolutionDir is not set when running dotnet build on a project. Solved this by simply adding a RootFolder variable and use that instead of SolutionDir. Before this fix you would get a cryptic sourcelink error:
```
C:\Users\Rick\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta2-19351-01\build\Microsoft.SourceLink.Common.targets(50,5): error : SourceRoot.SourceLinkUrl must contain a single wildcard '*': 'file:///raw/C:/git/duality/+refs/heads/*:refs/remotes/Barsonax/*/951bdcb2edba7800135da8abe7610a8b791a29e6/*'" [C:\git\duality\Source\Core\Primitives\DualityPrimitives.csproj]
```
- Updated sourcelink as it has been out of beta for a while. This also turned the …
> fix dotnet build not working
