AdamsLair/duality

Duality/DualityApp.cs

Just a tip: Duality should be targeted for Windows 10 too, otherwise running Duality on Windows 10 makes it think it is running on a Windows 8 environment.
See https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx

Added Windows 10 friendly name

---

Duality/Components/Renderers/AnimSpriteRenderer.cs

In light of this issue here:
https://github.com/AdamsLair/duality/issues/253
The removed code would not be executed, and as such was deemed to be harmless to remove in the above mentioned issue.
And, uh, sorry if the pull request seems... small. This is the only thing I could actually do.

Removed redundant code in AnimSpriteRenderer.

---

DualityEditorPlugins/SceneView/Modules/SceneView.cs

What I had to do:
1) Removed the check for a single selection when deciding if the "new" context menu item should be shown
2) Looped over the SelectedNodes property rather than just SelectedNode. This forced me to track the added nodes so that we could select them later. Selecting them inside the foreach loop would have modified the enumerable.
I checked and verified that this does not overwrite Component's if they already exist on a GameObject.

Added the ability to add components to multiple selected GameObjects

---

Duality/Resources/RenderTarget.cs

_A small usability addition_
When assigning textures to the render target, first it checks if the texture's size is set correctly (e.g. not 0). If not, it sends an error message to the user, and returns early.
This helps mostly beginner users, as it is not trivial that texture size has to be set before assigning.

RenderTarget checks Texture size

---

Duality/PluginManager.cs
DualityEditorPlugins/Tilemaps/CamViewStates/TilemapTools/ITilemapToolEnvironment.cs

This is a tiny pull request with no impact on the actual code itself, just fixes two warnings for two XML documentation comments thrown by Visual Studio.
(First pull request was based off of the wrong branch, this one is correct, hopefully)

Fixed two warnings about XML documentation comments.

---

DualityEditorPlugins/EditorBase/PropertyEditors/ComponentPropertyEditor.cs

Fix of issue #382 
There are multiple ways to solve this. The one 'below' seemed the best, because:
* it's simple
* it's nonsene to check wheter the component we're going to remove has itself as a dependency
enjoy 🍕

Can't delete a Component if RequiredComponent missing

---

DualityEditorPlugins/EditorBase/PreviewGenerators/PixmapPreviewGenerator.cs

Fixes [#405
](https://github.com/AdamsLair/duality/issues/405)

Fixes crash after creating a texture from an empty pixmap

---

DualityEditor/Sandbox.cs

Added a temporary scene in the sandbox.cs, so the sandbox restores the started scene.
Issue #377

Sandbox Returns to Started Scene After Stopping

---

Source/Platform/DefaultOpenTK/Backend/Graphics/NativeWindow.cs

This change in NativeWindow.OnUserDataChanged performs a check to verify if there is really the need to update/recreate the window, based on its current and the new settings, and allows to switch the mouse cursor visibility at runtime.

Better management of UserData changes

---

Source/Core/Duality/Components/Transform.cs

As discussed on Discord, the `MoveTo(Vector2)` and `MoveToAbs(Vector2)` methods of `Transform` are slightly changed, not resetting the Z coordinate of the position by simply casting to `Vector3`. I did not find any similar methods or usages in the solution.

MoveTo(Vector2) and MoveToAbs(Vector2) not changing Z coordinate

---

Source/Platform/DefaultOpenTK/Backend/Graphics/NativeWindow.cs

Allows to programmatically resize a resizeable window.
Although it looks a non-sense, I feel it's more counter-intuitive the fact that specifically setting a desired GfxHeight and Width in UserData gets ignored if the window is already resizeable by the user.
This normalizes the behavior of setting UserData and could be used, for example, to enforce a minimum/maximum window size, while leaving the user free to resize it between said limits.
*also, I think I didn't mess up the alignment this time* :)

NativeWindow

---

Source/Plugins/EditorModules/LogView/Modules/LogView.cs

Fixed a crash that would occur when closing the editor while the `LogView` is undocked.
Closes issue #500.

Potential LogView crash fix.

---

Source/Core/Duality/Resources/Font.cs

Lets try this again :D
_Fixed a NullReferenceException when the parameter of MeasureText (Font.cs) is null_

Fixed NullReferenceException in MeasureText

---

Source/Plugins/Tilemaps/Core/Tilemaps/Components/TilemapRenderer.cs

The current solution works correctly only with the `TilemapRenderer.Origin` set to `TopLeft`. This code works for every alignment case. (I assume that the function should return the tile position in the `TilemapRenderer.GameObj`'s local coordinate system.)

Fix GetLocalPosAtTile

---

Source/Editor/DualityEditor/Forms/NewProjectDialog.Designer.cs

Potential fix for minor issue #542, All tests are still passing after changing the tab order of the form. (Within the code its self the tab order does look like nonsense, however, the tab order on the form is now correct and behaves as expected.
All tests remain passing.

Fix for backwards tab order on new project dialog (#542)

---

Source/Plugins/EditorModules/CamView/CamViewStates/RigidBodyEditor/RigidBodyEditorCamViewState.cs

When you select a rigidbody tool in the rigidbody editor view and deselect the current gameobject, the tool keeps selected. As soon as you click somewhere in the view, the editor throws an exception.
[Click for full size
](https://gfycat.com/LameHighGrayling)
So this bug is now fixed with this tiny pull request.

Fixed a bug in the rigidbody editor

---

Source/Editor/DualityEditor/Forms/ObjectRefSelectionDialog.Designer.cs
Source/Editor/DualityEditor/Forms/ObjectRefSelectionDialog.cs

Implemented #606. The implementation follows almost exactly as described in the issue text. There is one decision I made that is debatable, however.
The ReferenceNode class has three Reference properties that had public get/setters. With the edits I made, the Image property is assigned within the inspector based on the value of the Reference property passed into the constructor. If these properties were left with public setters, some later code could set these Reference properties to a new object that could need a different image than the one originally set in the constructor. The simplest solution was to make the setters private. Now, future uses of this class avoid a possible bug.
The alternative is to change the getter/setters to use private backing fields and to update the Image …

Object ref dialog icons

---

Source/Platform/DefaultOpenTK/Backend/Graphics/GraphicsBackend.cs
Source/Platform/DefaultOpenTK/CorePlugin.cs

Fixed a bug where DefaultOpenTKBackendPlugin would initialize OpenTK even if Duality did not select it as the graphics backend

Default graphics backend now follows init rules

---

.nuget/packages.config
Duality.sln

#634: removing solution level packages

---

Source/Editor/DualityEditor/DualityEditor.csproj
Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs
Source/Editor/DualityEditor/Utility/SerializableReferenceWrapper.cs
Source/Editor/DualityEditor/Utility/SerializableWrapper.cs

Created a SerializableReferenceWrapper class to store references to objects through serialization. All that gets serialized is a long value which is used to lookup the object in a Dictionary<long, object>. Addresses #653.
All existing uses of the SetWrappedData DataObject extension method now use this wrapper except for the VectorPropertyEditor and SetIColorData. Both will end up using SerializableWrapper and a copy will be created but this maintains the current functionality as those are both value types.

#653 Serializable References

---

Source/Editor/DualityEditor/AssetManagement/Import/ExtMethodsIAssetImportEnvironment.cs

The extension method on IAssetImportEnvironment, HandleAllInput, now handles a null predicate. The documentation comment indicates that passing a null predicate should be allowed: "If no predicate is specified, this method will try to handle all available input." but it would instead throw a null reference exception when evaluating a null predicate.

HandleAllInput Null Predicate Fix

---

Source/Platform/DefaultOpenTK/Backend/Audio/NativeAudioSource.cs

In case that audio stream contains no data (even first call to `IAudioStreamProvider.ReadStream(...)` returns false) the `NativeAudioSource` is stuck in `streamWorkerQueue`. Because of this, the source is never freed up and also the `ReadStream` method of `IAudioStreamProvider` is constantly called.
As a fix, I am setting strStopReq to EndOfStream because this is what actually happens. Then I also need to modify condition which is stopping the streaming. I tested this on sample project and also with my custom stream provider. It should handle correctly streams of any lengths (empty, shorter than initial buffers, shorter than one buffer, infinitely long).

Fix audio source releasing when stream is empty

---

Source/Editor/DualityEditor/Controls/PropertyEditors/IColorDataPropertyEditor.cs
Source/Editor/DualityEditor/Controls/PropertyEditors/VectorPropertyEditor.cs
Source/Editor/DualityEditor/DualityEditor.csproj
Source/Editor/DualityEditor/Extensibility/DataConversion/ConversionData.cs
Source/Editor/DualityEditor/Extensibility/DataConversion/ConvertOperation.cs
Source/Editor/DualityEditor/Utility/Extensions/DataObjectStorage.cs
Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs
Source/Editor/DualityEditor/Utility/SerializableReferenceWrapper.cs
Source/Editor/DualityEditor/Utility/SerializableWrapper.cs
Source/Plugins/EditorBase/DataConverters/GameObjFromPrefab.cs
Source/Plugins/EditorBase/DataConverters/PrefabFromGameObject.cs
Source/Plugins/EditorBase/PropertyEditors/ComponentRefPropertyEditor.cs
Source/Plugins/EditorBase/PropertyEditors/GameObjectRefPropertyEditor.cs
Source/Plugins/EditorBase/PropertyEditors/ObjectRefPropertyEditor.cs
Source/Plugins/EditorModules/ProjectView/Modules/ProjectFolderView.cs
Source/Plugins/EditorModules/SceneView/Modules/SceneView.cs
Test/Editor/DualityEditorTests.csproj
Test/Editor/Utility/DataObjectExtensionsTest.cs

Added support for Reference and Value data format to DataObject extension methods when using SerializedWrappers. In the process, did general cleanup and bugfixes of the ExtMethodsDataObject file and improved API in various areas. See #655.
- Added support for reference and value formatted data.
- Added unit tests for most of the code in ExtMethodsDataObject. ~75% coverage.
- Added TryGet methods and changed most code that used Contains/Get to use TryGet instead.
- Added support for automatically converting reference data stored in a DataObject to value data. DeepClones the reference data.
- Changed WrappedData API to take `IEnumerable<object>` rather than `object`
- Fixed bugs in conversion of strings to IColorData
There remain two issue I'd like to get checked.
1. Should …

DataObject Extension Improvements

---

Source/Plugins/EditorModules/ObjectInspector/Modules/ObjectInspector.cs

Addressed #244 by saving `ObjectInspectors` `ExpandState` object to UserData.
Depends on [this PR from winforms project](https://github.com/AdamsLair/winforms/pull/7).
Nothing much to say here. Along the way I also fixed a bug related to the expand state tracking. New components were not respecting the expand state:
1. Create an object (A). Add a component. 
2. Create a new object (B). Add the same component and expand it.
3. Switch back to object (A). Notice it is expanded (as expected).
4. Create a new object (C). Add the same component. Notice is is not expanded.
5. Switch to object (A). Notice the component is not expanded.
4 and 5 are where you can notice the bug. New components were always collapsed and they would then overwrite the expand state for that component.

#244 Expand State saved in UserData

---

Source/Core/Duality/Utility/ReflectionHelper.cs

This is a PR addressing Issue #677.
All writes to class variables in the ReflectionHelper class have been wrapped in lock statements to compensate for potential of multiple threads concurrently modifying the collections.

Fix for threading issue in ReflectionHelper

---

Source/Core/Duality/Components/Camera.cs

These changes apply the correct screen space transformation required to correctly map from the Duality window to the virtual viewport described by the Camera's `TargetRect` property.
These changes are required for the correct implementation of PR #688.

Management of TargetRect in GetWorld/ScreenPos

---

Source/Plugins/Tilemaps/Editor/TilesetEditorModes/AutoTileTilesetEditorMode.cs

This PR is a fix for issue #526. This issue is caused when the TilesetAutoTileInput instance is no longer in the editor object selection.
When a user uses auto-tile mode, the current layer's TilesetAutoTileInput instance is added to the global object selection. However, if a user then selects something else (such as a tilemap drawing tool), it can no longer retrieve the instance. This means that subsequent UI painting will draw the tile but not apply any darkening/highlighting because TilesetView_PaintTiles first checks if that instance is null.
This commit modifies the auto-tile mode so that it stores a local instance of the input object. It will still add it to the global selection when the layer is selected, but it no longer relies on value itself.
Please let me know if there are any …

#526 Fix for Tileset Editor drawing when out of focus

---

Source/Editor/DualityEditor/DualityEditor.csproj
Source/Editor/DualityEditor/PackageManagement/PackageManager.cs
Source/Editor/DualityEditor/packages.config
Test/Editor/DualityEditorTests.csproj
Test/Editor/packages.config

#711 Updated nuget.core to 2.14

---

Source/Plugins/Tilemaps/Editor/Modules/SourcePaletteTilesetView.cs

Very simple fix to #690. Essentially just a check whenever selected tiles are updated that they are within the bounds of the selectable tiles. If this isn't the case, the selection is deselected entirely.

690 - Fixed incorrect tileset selection on resizing palette

---

Source/Core/Duality/Duality.csproj
Source/Core/Duality/packages.config
Source/Editor/DualityEditor/DualityEditor.csproj
Source/Editor/DualityEditor/packages.config
Source/Platform/DefaultOpenTK/DefaultOpenTK.Core.csproj
Source/Platform/DefaultOpenTK/packages.config
Source/Platform/DefaultOpenTKEditor/DefaultOpenTK.Editor.csproj
Source/Platform/DefaultOpenTKEditor/packages.config
Source/Plugins/EditorBase/EditorBase.Editor.csproj
Source/Plugins/EditorBase/packages.config
Source/Plugins/EditorModules/CamView/CamView.Editor.csproj
Source/Plugins/EditorModules/CamView/packages.config
Source/Plugins/EditorModules/HelpAdvisor/HelpAdvisor.Editor.csproj
Source/Plugins/EditorModules/HelpAdvisor/packages.config
Source/Plugins/EditorModules/LogView/LogView.Editor.csproj
Source/Plugins/EditorModules/LogView/packages.config
Source/Plugins/EditorModules/ObjectInspector/ObjectInspector.Editor.csproj
Source/Plugins/EditorModules/ObjectInspector/packages.config
Source/Plugins/EditorModules/PackageManagerFrontend/PackageManagerFrontend.Editor.csproj
Source/Plugins/EditorModules/PackageManagerFrontend/packages.config
Source/Plugins/EditorModules/ProjectView/ProjectView.Editor.csproj
Source/Plugins/EditorModules/ProjectView/packages.config
Source/Plugins/EditorModules/SceneView/SceneView.Editor.csproj
Source/Plugins/EditorModules/SceneView/packages.config
Source/Plugins/Tilemaps/Editor/Tilemaps.Editor.csproj
Source/Plugins/Tilemaps/Editor/packages.config
Test/Core/DualityTests.csproj
Test/Core/packages.config
Test/Editor/DualityEditorTests.csproj
Test/Editor/packages.config

Solves #736
After this the nuget and netstandard branch need to get updated again (should make the changes in those branches alot smaller though).

Migrated all projects to packagereference

---

Directory.Build.props

This enables [Source Link](https://github.com/dotnet/sourcelink) information on all compatible projects in the repository. Should it only happen for projects under Source instead?
The Source Link documentation [recommends separating the PDBs into symbol packages](https://github.com/dotnet/sourcelink#alternative-pdb-distribution) instead of packaging them in the main nupkg files. That can probably be done in NightlyBuilder by passing an additional parameter to `nuget pack` and changing the PDB type if you want it.
Related to #746

enable sourcelink

---

Source/Core/Duality/Components/Camera.cs

Adjusted allowed Editor ranges for FarZ (and NearZ) in Camera.cs to match reasonableMin. Editor now does not allow values to be set below this.

Addressing Bug #753: Prevent FarZ-Property of the camera component to be 0. 

---

Source/Plugins/Tilemaps/Core/Tilesets/Tileset.cs
Source/Plugins/Tilemaps/Core/Tilesets/TilesetCompiler.cs
Source/Plugins/Tilemaps/Core/Tilesets/TilesetCompilerOutput.cs
Source/Plugins/Tilemaps/Editor/Modules/TilemapToolSourcePalette.cs

Fairly simple change that adds an `int EmptyTileIndex` to the `Tileset` which will be used by the `TileMapToolSourcePalette` when making a new selection of tiles. This value is computed at `Tileset` compile time. It is set to -1 if there are no empty tiles.

#731 - Use a default empty tile for all empty tiles

---

Source/Plugins/EditorModules/ProjectView/Modules/ProjectFolderView.cs

As described in the discussion of issues #773, this PR inhibits the possibility to rename a Resource as nothing, removing the issue itself.
The affected node will be flashed as well, to focus the attention on the fact that it wasn't renamed.

Block the renaming of a resource to a null or empty string.

---

README.md

Now that master is essentially in 4.0 alpha state, we should keep the last released 3.x version as an archive branch, as we did with 1.x and 2.x. The archive branch is already created, but this PR adds a 3.x status badge to the readme page.

Created v3.x Archive Branch + Status Badge

---

Test/Core/Drawing/VertexBatchTest.cs
Test/Core/DualityTests.csproj
Test/Core/Utility/GarbageCollectionTestSet.cs
Test/Core/Utility/GarbageCollectionUtils.cs

Moved assert code to check if the resource that a weakreference points to is alive or not after garbage collecting to a separate method. This defeats the fact that in debug mode instances might be kept alive for longer than strictly needed. Disabling inlining defeats any optimizations that might happen in release mode.
The end result is a garbage collection test that works both in debug and release.

#719 Fixed vertex locking test failing in debug mode

---

Samples/AudioHandling/AudioHandling.Sample.Core.csproj
Samples/BasicMenu/BasicMenu.Sample.Core.csproj
Samples/BasicShaders/BasicShaders.Sample.Core.csproj
Samples/Benchmarks/Benchmarks.Sample.Core.csproj
Samples/CameraController/CameraController.Sample.Core.csproj
Samples/CustomRenderingSetup/CustomRenderingSetup.Sample.Core.csproj
Samples/DualStickSpaceShooter/DualStickSpaceShooter.Sample.Core.csproj
Samples/DynamicLighting/Core/DynamicLighting.Sample.Core.csproj
Samples/FlapOrDie/FlapOrDie.Sample.Core.csproj
Samples/InputHandling/InputHandling.Sample.Core.csproj
Samples/ParticleSystem/ParticleSystem.Sample.Core.csproj
Samples/Physics/Physics.Sample.Core.csproj
Samples/SmoothAnimation/SmoothAnimation.Sample.Core.csproj
Samples/Steering/Steering.Sample.Core.csproj
Samples/Tilemaps/Tilemaps.Sample.Core.csproj
Source/Core/Duality/Duality.csproj
Source/Core/Physics/DualityPhysics.csproj
Source/Core/Primitives/DualityPrimitives.csproj
Source/Plugins/Compatibility/Compatibility.Core.csproj
Source/Plugins/Tilemaps/Core/Tilemaps.Core.csproj

Just a small cleanup, the `<?xml version="1.0" encoding="utf-8"?>` is not needed with sdk style projects

Remove unneeded xml version from csprojs

---

Build/NuGetPackageSpecs/DefaultOpenTKBackend.Core.nuspec

Moved the openalsoft libraries to the runtimes\any\native folder in the nuget package
In the template I had to add `<RuntimeIdentifier>any</RuntimeIdentifier>` to the csproj so that it knows to pick up the any folder.
This solves the warning you otherwise get because it was trying to load the native dll's as a non native dll.
Solves #787

Fixed opentk Resolved file has a bad image warning

---

Directory.Build.props

If one of the `Content` folders, either in any of the sample projects `Content` working directories contains source code of a custom game plugin, the build of the solution will fail due to it being included in the build by accident.
This PR fixes the issue by adding a global msbuild ignore for files in `Content` folder hierarchies.

Fixed compiler errors when any Content folder contains source code

---

Source/Editor/DualityEditor/AssetManagement/AssetInternalHelper.cs
Source/Editor/DualityEditor/AssetManagement/Import/AssetFirstImportOperation.cs
Source/Editor/DualityEditor/AssetManagement/Import/AssetReImportOperation.cs
Source/Editor/DualityEditor/DualityEditorApp.cs
Source/Editor/DualityEditor/FileEventManager.cs
Source/Editor/DualityEditor/Forms/PublishGameDialog.cs
Source/Editor/DualityEditor/Utility/EditorHelper.cs

Revision of #823
Decided to keep DualityEditor/DualityLauncher in the root for now as that doesn't require much changes in duality:
```
[Project Folder]
|
+- [Project].sln
|
+- DualityEditor.exe
+- Data
+- Plugins
+- all the other project files and binaries
|
+- Import
|
+- Source
+- Launchers
+- GameLauncher
+- GameEditor
+- Plugins
+- GamePlugin
```

revised project structure with dualityeditor still at the root

---

Source/Core/Duality/Utility/RawList.cs
Test/Core/Utility/RawListTest.cs

As noted in #820, the `RawList<T>` class can benefit from newly available ref-returns in C# 7.3 for its indexer implementation. Since this is a breaking change for v4.0, it also was a good opportunity to rework and extend some of its API to better address its core use case.
This PR adds several small improvements, as well as a by-ref indexer for `RawList<T>`. For a detailed list, see the individual commits, which have been structured so each one represents a group of changes.

Improved RawList API, Implementation and Tests

---

Source/DualityTemplates/Templates/SolutionTemplate/Source/Launchers/GameEditor/Properties/launchSettings.json
Source/DualityTemplates/Templates/SolutionTemplate/Source/Launchers/GameLauncher/Properties/launchSettings.json

In the current alpha2 release, the run / debug buttons for `GameLauncher` and `GameEditor` in Visual Studio are broken, as their working directory is off by one - probably a regression due to recent folder structure changes.
This PR fixes the launch settings and also provides more descriptive names for the "Run" button / debug profile.

Fixed VS Debug / Run for launchers in Duality project template

---

.gitignore
Benchmarks/DualityBenchmarks/CloneProviderBenchmarks.cs
Benchmarks/DualityBenchmarks/DualityBenchmarks.csproj
Benchmarks/DualityBenchmarks/PrefabBenchmarks.cs
Benchmarks/DualityBenchmarks/Program.cs
Benchmarks/DualityBenchmarks/SerializerBenchmarks.cs
Benchmarks/DualityBenchmarks/SpecificCloningBenchmarks.cs
Duality.sln
Source/Core/Duality/Serialization/Serializer.cs
Test/Core/Cloning/CloneProviderTest.cs
Test/Core/Cloning/SpecificCloningTest.cs
Test/Core/InitDualityAttribute.cs
Test/Core/Resources/PrefabTest.cs
Test/Core/Serialization/SerializerTest.cs
Test/Core/Testing/TestHelper.cs

Moved all our benchmarks in our unit tests to a separate benchmarkdotnet project.
How to use:
- cd to Benchmarks\DualityBenchmarks
- Run `dotnet run -c Release --list tree` to view the available benchmarks
- Run `dotnet run -c Release --filter CloneProviderBenchmarks` to run the CloneProviderBenchmarks
TODO:
- Some benchmarks are running alot of itterations. This is a leftover of the setup in the unit tests and is usually not needed unless you are interested in how something scales. Change this to only run once or if scaling is important parameterize it so its easier to see the scaling (for example do 3 runs with the first run only 1 itteration, the second one 10 itterations etc). DONE
Rebased on https://github.com/AdamsLair/duality/pull/842

Migrate performance benchmarks in unit tests to benchmarkdotnet

---

Benchmarks/DualityBenchmarks/DualityBenchmarks.csproj
Benchmarks/DualityBenchmarks/Program.cs
Benchmarks/DualityBenchmarks/SerializerBenchmarks.cs

Changes:
- Set the correct output path for the benchmarks, this fixes the actually exception.
- Fail fast when debugging benchmarks
- Use DualityLauncher in the benchmark to unify code flow

Fix exception in cleanup of serialization benchmark due to working folder being wrong

---

Test/Core/InitDualityAttribute.cs
Test/Editor/InitDualityEditorAttribute.cs

Just a small cleanup since nunit provides a utility for setting the current directory already.
Also use `typeof(DualityTestsPlugin).Assembly.Location` for the location of the test plugin as thats cleaner and also actually fixes a potential bug as previously it would be set to `Duality.dll` instead of `DualityTests.dll`.

Cleanup InitDualityAttribute's

---

Source/Core/Duality/Serialization/Surrogates/XElementSurrogate.cs
Source/Core/Duality/Serialization/XmlSerializer.cs
Test/Core/Serialization/SerializerTest.cs

Serializing and deserializing `XElement` did not work properly before. This PR adds a `XElementSurrogate` which allows all serializers in duality to properly handle `XElement`.
Additionally `XmlSerializer` has a small extra modification to make the serialized xml more readable, without this change the serialized xml would end up as a base64 string.
TODO

Added XElement support to the serializer

---

.editorconfig

This style change makes it so that the explicit type is no longer needed when the type is apparent. This leads to more concise code and cleans up the find all references results without sacrificing readability.
Some examples:
Before:
```cs
List<string> auxilLibs = new List<string>();
```
After
```cs
var auxilLibs = new List<string>();
```
Before
```cs
ICmpInitializable cInit = this as ICmpInitializable;
```
After
```cs
var cInit = this as ICmpInitializable;
```
However a case like this will still require a explicit type. Even though a method named `CreateCmpInitializable` would probably return a `ICmpInitializable` its not a given as method can be given a name that might not properly communicate its intent.
```cs
ICmpInitializable cInit = CreateICmpInitializable();
```
NOTE: this PR only …

csharp_style_var_when_type_is_apparent to true

---

Source/Editor/DualityEditor/Forms/AboutBox.Designer.cs
Source/Editor/DualityEditor/Forms/AboutBox.cs

Found this bug while exploring the codebase, which was preventing the About dialog from displaying.

Fix display of version info to no longer include launcher version.
